[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ensp-toolkit"
version = "0.1.0"
description = "Programmatic eNSP network topology and VRP config generator"
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
ensp-cli = "ensp.cli:main"

[tool.setuptools]
packages = ["ensp"]
package-dir = {ensp = "."}
